<a href="https://colab.research.google.com/github/hamzaqarni1/DeepLearning/blob/main/Tutorial_1/Perceptron_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

class Perceptron (object):
  def __init__(self, eta=0.01, n_iter=10):
    self.eta = eta
    self.n_iter = n_iter
  def weighted_sum(self, X):
    return np.dot(X, self.w_[1:]) + self.w_[0]
    #Task 2:
  #ORIGINAL STEP FUNCTION
  #def predict(self, X):
  #  return np.where(self.weighted_sum(X) >= 0.0, 1, -1)

  #MODIFIED SIGMOID
  def predict(self, X):
      # 1. Get the weighted sum
      z = self.weighted_sum(X)

      # 2. Apply the Sigmoid mathematical formula
      sigmoid_output = 1.0 / (1.0 + np.exp(-z))

      # 3. Return 1 if probability is >= 0.5, otherwise return 0
      return np.where(sigmoid_output >= 0.5, 1, 0)
  def fit(self, X, y):
    self.w_ = np.zeros(1+X.shape[1])
    self.errors_ = []
    print("Weights:", self.w_)
    for _ in range(self.n_iter):
      errors = 0
      for xi, target in zip(X, y):
        y_pred = self.predict(xi)
        update = self.eta * (target - y_pred)
        self.w_[1:] += update * xi
        print("Updated Weights:", self.w_[1:])
        self.w_[0] += update
        errors += int(update != 0.0)
      self.errors_.append(errors)
    return self

In [47]:


df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
df = shuffle(df)
df.head()


,0,1,2,3,4
31,5.4,3.4,1.5,0.4,Iris-setosa
45,4.8,3.0,1.4,0.3,Iris-setosa
86,6.7,3.1,4.7,1.5,Iris-versicolor
108,6.7,2.5,5.8,1.8,Iris-virginica
140,6.7,3.1,5.6,2.4,Iris-virginica


In [48]:
X = df.iloc[:, 0:4].values
y = df.iloc[:,4].values
print(X[0:5])
print(y[0:5])
from sklearn.model_selection import train_test_split
train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.3)
train_labels = np.where(train_labels == 'Iris-setosa', 1, 0)
test_labels = np.where(test_labels == 'Iris-setosa', 1, 0)
print('Train data:', train_data[0:2])
print('Train labels:', train_labels[0:2])
print('Test data:', test_data[0:2])
print('Test labels:', test_labels[0:2])


[[5.4 3.4 1.5 0.4]
 [4.8 3.  1.4 0.3]
 [6.7 3.1 4.7 1.5]
 [6.7 2.5 5.8 1.8]
 [6.7 3.1 5.6 2.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica']
Train data: [[6.2 2.8 4.8 1.8]
 [6.3 2.9 5.6 1.8]]
Train labels: [0 0]
Test data: [[7.1 3.  5.9 2.1]
 [5.4 3.4 1.7 0.2]]
Test labels: [0 1]


In [49]:
#from sklearn.linear_model import Perceptron
perceptron = Perceptron(eta=0.1, n_iter=10)
perceptron.fit(train_data, train_labels)

test_preds = perceptron.predict(test_data)
print(test_preds)


Weights: [0. 0. 0. 0. 0.]
Updated Weights: [-0.62 -0.28 -0.48 -0.18]
Updated Weights: [-0.62 -0.28 -0.48 -0.18]
Updated Weights: [-0.62 -0.28 -0.48 -0.18]
Updated Weights: [-0.62 -0.28 -0.48 -0.18]
Updated Weights: [-0.62 -0.28 -0.48 -0.18]
Updated Weights: [-0.62 -0.28 -0.48 -0.18]
Updated Weights: [-0.04  0.12 -0.36 -0.16]
Updated Weights: [ 0.5   0.46 -0.21 -0.12]
Updated Weights: [ 0.5   0.46 -0.21 -0.12]
Updated Weights: [-0.1   0.16 -0.69 -0.3 ]
Updated Weights: [ 0.4   0.46 -0.53 -0.28]
Updated Weights: [-0.34  0.18 -1.14 -0.47]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.49 -0.99 -0.46]
Updated Weights: [ 0.15  0.4

In [50]:
from sklearn.metrics import accuracy_score
y_preds = perceptron.predict(test_data)
accuracy = accuracy_score(test_labels, y_preds)
print('Accuracy:', round(accuracy, 2) * 100, '%')


Accuracy: 100.0 %


In [51]:
#Task 1

import ast
manual_input = [ast.literal_eval(input("Please Input values for (sepal length, sepal width, petal length, and petal width) e.g. [2.2, 3.3, 4.4, 5.0] (Note: Do not forget brackets [] and commas ,)"))]


test_preds = perceptron.predict(manual_input)
print(test_preds)
print(f"Model's Prediction: {test_preds} - { 'Iris setosa' if test_preds == 1 else 'not Iris Setosa' }")


Please Input values for (sepal length, sepal width, petal length, and petal width) e.g. [2.2, 3.3, 4.4, 5.0] (Note: Do not forget brackets [] and commas ,)[5.0,3.4,1.5,0.2]
[1]
Model's Prediction: [1] - Iris setosa
